version: '3'

services:
  app:
    build:
      context: app
    ports:
      - '5000'
    volumes:
      - ./app/:/app
    networks:
      - database_default

  nginx:
    image: nginx:latest
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - app
    ports:
      - '81:81'
    restart: always
    networks:
      - database_default

networks:
  database_default:
    external: true
    driver: bridge
    name: database_default
